name: CI - Test & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 httpx

      - name: Lancer les tests
        env:
          PYTHONPATH: .
        run: pytest tests/

      - name: Linting avec flake8
        run: flake8 app/ tests/

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build de l'image Docker
        run: docker build -t churn-api .
